### PR TITLE
[FEATURE] First Accordion Element closed or open

### PR DESCRIPTION
**Pull request by linawolf**
Make configurable weather the first accordion is opened or closed. The default behavior (first opened) will be kept

fixes https://github.com/laxap/bootstrap_grids/issues/55

### CODE REVIEW

**Review by jkkoenig — COMMENTED** [review]
This works for me in Typo3 V 10.4 Thank you

**Comment by RozbehSharahi** [comment]
Hello,

thank you for the patch. As it was based on old code and contained unrelated changes, the feature was introduced by this PR:

https://github.com/RozbehSharahi/bootstrap_grids/pull/74

Kind regards

**Comment by outdoorsman** [comment]
So excited to see you working on these pull requests @RozbehSharahi. I have fix some issues in the TYPO3 version 12 branch that fixes some issues in the Bootstrap 5 accordions and tabs. I will try to submit that pull request soon. I just wasn't sure if things were being maintained or if the pull requests were going to be used.

**Comment by RozbehSharahi** [comment]
Ok, but to be honest, I don't see how you have this on typo3 12 if there is no Container grid elements extension for typo3 12.

**Pull request closed without merging**
